### ISSUE TITLE
Add a terminal prompt character

### ISSUE THREAD

**Issue by jghibiki** [moe-serifu-circle/moe-serifu-agent#31]
From my experience it is common that when user input is expected to print a prompt character to make it easily visible to determine that the program is waiting for input and not hanging.

e.g.

```shell
give me input:

```
vs 

```shell
give me input:
>
```

**Comment by dekarrin** [comment]
Mm, this one is tricky to do quickly due to modularity. The input subsystem does not have direct access to the output subsystem. This is by design due to the principle of keeping them modular so that input is not dependent on a particular kind of input, though this might well be a good case for joining them back together.

At any rate, the current method of cross-module communication (as opposed to dependent module communication) is to fire an event that the receiving module is subscribed to. This would be another way to accomplish this task; perhaps the output system could subscribe to the "input entered" event and print the prompt then... though, it would be better if it detected an event that the last entered command had completed, and thus it should print the prompt. Gotta be careful not to race with the user entering additional input in between though.
